# Begin

In [1]:
import os 
import sys 
import copy
from collections import namedtuple, defaultdict, Counter 
import itertools
import json
import datetime
import pprint
import re
import pickle
import dataclasses 
from dataclasses import dataclass 
import IPython
from enum import Flag, StrEnum, auto 

from tqdm.notebook import tqdm
import numpy as np
import einops
import pandas as pd

import torch

project_root_path = '${PROJECT_ROOT_PATH}' 
project_root_path = ! git rev-parse --show-toplevel
project_root_path = project_root_path[0]

sys.path.append('.')
from bundle import *
sys.path.append(os.path.join(project_root_path, 'lib'))
from utils import * 
from logging_utils import *
from model_registry import *

# Setup

In [2]:
LOG = Logging.get()
RNG = np.random.default_rng()

class ExecMode(StrEnum):
    MASTER_NOTEBOOK = auto()
    LAUNCH_NOTEBOOK = auto()
    LAUNCH_MODULE = auto()

CONFIG = namedtuple('Config', 
                    'project_root_path, project_root_uri, subproject_path, data_path, private_data_path, run_path, ' + 
                    'self_fname, self_name, ' +
                    'subproject_name,' +
                    'is_cuda, cuda_device, exec_mode, is_interactive')(
    project_root_path=project_root_path,
    project_root_uri=f'com.develorium.{os.path.basename(project_root_path)}',
    subproject_path=os.path.abspath('.'),
    data_path=os.path.join(project_root_path, 'data'),
    private_data_path=None,
    run_path='',
    self_fname='',
    self_name='',
    subproject_name='',
    is_cuda=torch.cuda.is_available(),
    cuda_device='cuda' if torch.cuda.is_available() else 'cpu',
    exec_mode=ExecMode.MASTER_NOTEBOOK,
    is_interactive=True,
)

if IPython.get_ipython() is None:
    module_fname = __file__
    module_basename = os.path.basename(module_fname)
    module_name, _ = os.path.splitext(module_basename)
    
    CONFIG = CONFIG._replace(self_fname=module_fname, self_name=module_name)
    CONFIG = CONFIG._replace(exec_mode=ExecMode.LAUNCH_MODULE)
else:
    with open(IPython.get_ipython().kernel.config['IPKernelApp']['connection_file'], 'r') as cf:
        notebook_fname = json.load(cf)['jupyter_session']
        notebook_basename = os.path.basename(notebook_fname)
        notebook_name, notebook_ext = os.path.splitext(notebook_basename)
    
        m = re.match(r'(\w+)-Copy\d+$', notebook_name)
    
        if m: notebook_name = m.group(1) # e.g. Cuml is used to be launched from the copy of the notebook

        CONFIG = CONFIG._replace(self_fname=notebook_fname, self_name=notebook_name)
        
        is_launch = re.match(r'\w+-launch\d+$', notebook_name) is not None
        CONFIG = CONFIG._replace(exec_mode=ExecMode.MASTER_NOTEBOOK if not is_launch else ExecMode.LAUNCH_NOTEBOOK)

CONFIG = CONFIG._replace(is_interactive=CONFIG.exec_mode != ExecMode.LAUNCH_MODULE)

LOG.app_name = CONFIG.self_name
LOG.enable('syslog', not CONFIG.is_interactive)
LOG.enable('stdout', CONFIG.is_interactive)

CONFIG = CONFIG._replace(subproject_name=os.path.basename(os.path.dirname(CONFIG.self_fname)))
CONFIG = CONFIG._replace(run_path=os.path.join(project_root_path, 'run', CONFIG.subproject_name))
CONFIG = CONFIG._replace(private_data_path=os.path.join(CONFIG.data_path, CONFIG.subproject_name))
LOG(f'CONFIG=\n{pprint.pformat(CONFIG._asdict(), sort_dicts=False)}\n', when=CONFIG.is_interactive)
LOG(f'CONFIG={CONFIG._asdict()}', when=not CONFIG.is_interactive)

os.makedirs(CONFIG.private_data_path, exist_ok=True)

CONFIG=
{'project_root_path': '/home/misha/dev/mine/neurovision',
 'project_root_uri': 'com.develorium.neurovision',
 'subproject_path': '/home/misha/dev/mine/neurovision/12_rnn',
 'data_path': '/home/misha/dev/mine/neurovision/data',
 'private_data_path': '/home/misha/dev/mine/neurovision/data/12_rnn',
 'run_path': '/home/misha/dev/mine/neurovision/run/12_rnn',
 'self_fname': '/home/misha/dev/mine/neurovision/12_rnn/make_bundle.ipynb',
 'self_name': 'make_bundle',
 'subproject_name': '12_rnn',
 'is_cuda': False,
 'cuda_device': 'cpu',
 'exec_mode': <ExecMode.MASTER_NOTEBOOK: 'master_notebook'>,
 'is_interactive': True}

# Types

In [3]:
class TokenLevel(StrEnum):
    SYMBOL = auto()
    WORD = auto()

# TextPreprocessor

In [44]:
class TextPreprocessor:
    def __init__(self, token_level):
        match token_level:
            case TokenLevel.SYMBOL:
                self.split_line = self.split_line_symbol
                self.check_token = self.check_token_symbol
            case TokenLevel.WORD:
                self.split_line = self.split_line_word
                self.check_token = self.check_token_word
            case _:
                assert False, f'Unsupported {token_level=}'
        
    def remove_pg_envelope(self, text):
        start_indx = text.find('START OF THIS PROJECT')
        start_indx = text.find('START OF THE PROJECT') if start_indx < 0 else start_indx
        end_indx = text.find('End of the Project Gutenberg')
        end_indx = text.find('END OF THE PROJECT GUTENBERG') if end_indx < 0 else end_indx
        assert start_indx >= 0
        assert end_indx >= 0
        
        while text[start_indx] != '\n': 
            start_indx += 1
        
        while text[start_indx] == '\n':
            start_indx += 1
        
        while text[end_indx] != '\n':
            end_indx -= 1

        return text[start_indx:end_indx]

    SPLIT_CHARS = r'"\',.:;?!()\[\]=\+\*/—%…\-\$£_&'
    SYMS_SUBST_TAB = {
        'ï': 'i', 'é': 'e', 'ô': 'o', 'î': 'i', 'ê': 'e', 'æ': 'e', 'ä': 'a', 'ç': 'c', 'ö': 'o', 'à': 'a', 'ü': 'u', 'è': 'e',
        'œ': 'e', 'ù': 'u', 'ò': 'o', 'ā': 'a', 'á': 'a', 'ñ': 'n', 'ó': 'o', 'ú': 'u', 'û': 'u', '✠': '', '†': 'd.', 'ë': 'e', 'ſ': 's', '•': '-', '°': '', chr(0x338): '',
        
    }
    
    def preprocess(self, text):
        text = re.sub(r'[“”]', '"', text)
        text = re.sub(r'[‘’]', "'", text)
        text = re.sub(r'\r\n', '\n', text)
        text = re.sub(r'([^\n])\n([^\n])', r'\1 \2', text)
        text = re.sub(r'\n(\n)+', '\n', text)
        text = re.sub(r'-(-)+', '. ', text)
        text = re.sub(r'\.\.\.', '…', text)
        text = text.lower()
        text = ''.join(map(lambda sym: TextPreprocessor.SYMS_SUBST_TAB.get(sym, sym), text))
        uniq_syms = Counter(text)
        unsupported_syms = list(filter(lambda sym: not re.match(r'[a-z0-9\s' + TextPreprocessor.SPLIT_CHARS + ']', sym), uniq_syms.keys()))
        assert not unsupported_syms, f'Unsupported syms={unsupported_syms}'
        return text

    
    def split_line_symbol(self, line):
        line = re.sub(r'\s(\s)+', ' ', line)
        return list(filter(self.check_token_symbol, line))
        
    def split_line_word(self, line):
        r = []

        # Combination of line.split() and re.split() is used to retain SPLIT_CHARS as individual tokens but to remove separators (\s)
        # Note: re.split with grouping is a must - in opposite case separators will get lost
        for x in line.split():
            r.extend(filter(None, re.split(r'([' + TextPreprocessor.SPLIT_CHARS + r'])', x))) # filter is used to remove empty elements

        return r

    def check_token_word(self, token):
        return re.match(r'[\w' + TextPreprocessor.SPLIT_CHARS +  r']+', token)

    def check_token_symbol(self, token):
        return re.match(r'[\w ' + TextPreprocessor.SPLIT_CHARS +  r']+', token)

In [45]:
x = "the dog's   bark ran towards him, stopped."
print('|' + '|'.join(TextPreprocessor(TokenLevel.WORD).split_line(x)) + '|')
print('|' + '|'.join(TextPreprocessor(TokenLevel.SYMBOL).split_line(x)) + '|')

|the|dog|'|s|bark|ran|towards|him|,|stopped|.|
|t|h|e| |d|o|g|'|s| |b|a|r|k| |r|a|n| |t|o|w|a|r|d|s| |h|i|m|,| |s|t|o|p|p|e|d|.|

# Generate

## Configure

In [52]:
CHUNK_SIZE = 40
TOKEN_LEVEL = TokenLevel.SYMBOL
BUNDLE_FNAME = os.path.join(CONFIG.private_data_path, f'bundle_{CHUNK_SIZE}_{TOKEN_LEVEL.value}.pkl')
SOURCES = [
    'crime_and_punishment',
    'the_great_gatsby',
    'the_mysterious_island',
    'the_picture_of_dorian_gray',
    'ulysses',
]

## Generate

In [53]:
preprocessed_texts_dir_name = os.path.join(CONFIG.private_data_path, 'preprocessed')
os.makedirs(preprocessed_texts_dir_name, exist_ok=True)

source_to_text = {}
source_to_tokens = {}
df_sources = pd.DataFrame(dict(
    name=SOURCES,
    fname=list(map(lambda s: os.path.join(preprocessed_texts_dir_name, s + '.txt'), SOURCES)),
))

text_preprocessor = TextPreprocessor(TOKEN_LEVEL)

for row in df_sources.itertuples():
    mr = ModelRegistry(maven_group_id='org.gutenberg')
    text = mr.get_asset_content(row.name, 1, 'txt').decode('utf-8')
    text = text_preprocessor.remove_pg_envelope(text)
    text = text_preprocessor.preprocess(text)

    with open(row.fname, 'w', encoding="utf-8") as f:
        f.write(text)

    source_to_text[row.name] = text

vocab = Counter()
chunks = []

for iter_no, iter_name in enumerate(('Vocab', 'Tokens', 'Chunks')):
    if iter_no in [0, 1]:
        for source_name, text in source_to_text.items():
            lines = text.splitlines()
            tokens = [] # for each line will contain list of tokens, i.e. list of lists
            
            for line_ind, line in tqdm(enumerate(lines), total=len(lines), desc=f'{iter_name}, {source_name}'):
                line_tokens = text_preprocessor.split_line(line)
    
                if iter_no == 0:
                    vocab.update(line_tokens)
                else:
                    tokens.append(list(map(lambda t: vocab[t][0], line_tokens)))
                    
            source_to_tokens[source_name] = tokens

        if iter_no == 0:
            text_list, freq_list = zip(*vocab.most_common())
            ind_list = list(range(len(text_list)))
            vocab = dict(zip(text_list, zip(ind_list, freq_list))) # make dict: text -> (ind, freq)
    
    elif iter_no == 2:
        for source_name, tokens in source_to_tokens.items():
            source_ind = df_sources[df_sources.name == source_name].index.item()
            line_inds = [] # aligned with tokens (1-to-1 mapping), stamps every token with a line index

            for line_ind, line_tokens in enumerate(tokens):
                line_inds.extend([line_ind] * len(line_tokens))

            tokens = list(itertools.chain.from_iterable(tokens)) # flatten tokens list
            assert len(line_inds) == len(tokens)
            
            for start_ind in tqdm(range(len(tokens) - CHUNK_SIZE), desc=f'{iter_name}, {source_name}'):
                chunk = tokens[start_ind:start_ind+CHUNK_SIZE]
                assert len(chunk) == CHUNK_SIZE
                chunks.append((np.array(chunk), source_ind, line_inds[start_ind], line_inds[start_ind+CHUNK_SIZE-1]))
    
    else:
        assert False, (iter_no, iter_name)

text_list, ind_freq_list = zip(*vocab.items())
ind_list, freq_list = zip(*ind_freq_list)
df_vocab = pd.DataFrame(dict(
    text=text_list,
    freq=freq_list,
), index=ind_list)
chunk_list, source_id_list, start_line_ind_list, end_line_ind_list = zip(*chunks)
df_chunks = pd.DataFrame(dict(
    chunk=chunk_list,
    source_ind=source_id_list,
    start_line_ind=start_line_ind_list,
    end_line_ind=end_line_ind_list,
))
bundle = Bundle(df_sources=df_sources, df_vocab=df_vocab, df_chunks=df_chunks)

with open(BUNDLE_FNAME, 'wb') as f:
    pickle.dump(bundle, f)
    
LOG(f'Bundle generated and saved to "{BUNDLE_FNAME}"')

Downloading http://nexus:8081/repository/model-registry/org/gutenberg/crime_and_punishment/1/crime_and_punishment-1-fyodor_dostoyevsky.txt for asset with id=bW9kZWwtcmVnaXN0cnk6ZTFhM2E4NDI
Downloading http://nexus:8081/repository/model-registry/org/gutenberg/the_great_gatsby/1/the_great_gatsby-1-francis_scott_fitzgerald.txt for asset with id=bW9kZWwtcmVnaXN0cnk6ZmNlNjk4Ng
Downloading http://nexus:8081/repository/model-registry/org/gutenberg/the_mysterious_island/1/the_mysterious_island-1-jules_verne.txt for asset with id=bW9kZWwtcmVnaXN0cnk6ZjhiOTA4ZTQ
Downloading http://nexus:8081/repository/model-registry/org/gutenberg/the_picture_of_dorian_gray/1/the_picture_of_dorian_gray-1-oscar_wilde.txt for asset with id=bW9kZWwtcmVnaXN0cnk6MjZlM2NhMjg
Downloading http://nexus:8081/repository/model-registry/org/gutenberg/ulysses/1/ulysses-1-james_joyce.txt for asset with id=bW9kZWwtcmVnaXN0cnk6M2RmOTJhY2E

Vocab, crime_and_punishment:   0%|          | 0/3970 [00:00<?, ?it/s]

Vocab, the_great_gatsby:   0%|          | 0/1653 [00:00<?, ?it/s]

Vocab, the_mysterious_island:   0%|          | 0/4905 [00:00<?, ?it/s]

Vocab, the_picture_of_dorian_gray:   0%|          | 0/1527 [00:00<?, ?it/s]

Vocab, ulysses:   0%|          | 0/7180 [00:00<?, ?it/s]

Tokens, crime_and_punishment:   0%|          | 0/3970 [00:00<?, ?it/s]

Tokens, the_great_gatsby:   0%|          | 0/1653 [00:00<?, ?it/s]

Tokens, the_mysterious_island:   0%|          | 0/4905 [00:00<?, ?it/s]

Tokens, the_picture_of_dorian_gray:   0%|          | 0/1527 [00:00<?, ?it/s]

Tokens, ulysses:   0%|          | 0/7180 [00:00<?, ?it/s]

Chunks, crime_and_punishment:   0%|          | 0/1123330 [00:00<?, ?it/s]

Chunks, the_great_gatsby:   0%|          | 0/264811 [00:00<?, ?it/s]

Chunks, the_mysterious_island:   0%|          | 0/1102106 [00:00<?, ?it/s]

Chunks, the_picture_of_dorian_gray:   0%|          | 0/426000 [00:00<?, ?it/s]

Chunks, ulysses:   0%|          | 0/1501519 [00:00<?, ?it/s]

Bundle generated and saved to "/home/misha/dev/mine/neurovision/data/12_rnn/bundle_40_symbol.pkl"

# Verify

## Load

In [54]:
%%time

with open(BUNDLE_FNAME, 'rb') as b:
    bundle = pickle.load(b)

chunks = np.array(bundle.df_chunks['chunk'].values.tolist())
assert chunks.shape[1] == CHUNK_SIZE
LOG(f'Bundle with chunks loaded from "{BUNDLE_FNAME}"')

Bundle with chunks loaded from "/home/misha/dev/mine/neurovision/data/12_rnn/bundle_40_symbol.pkl"
CPU times: user 5.98 s, sys: 1.33 s, total: 7.3 s
Wall time: 7.29 s

## Verify vocab

In [55]:
bundle.df_vocab.head()

  text    freq
0       771179
1    e  425808
2    t  314623
3    a  278218
4    o  268271

In [56]:
bundle.df_vocab.tail()

   text  freq
56    %     6
57    &     4
58    $     2
59    =     2
60    +     1

## Verify chunks

In [57]:
# @launchit.disable
columns = defaultdict(list)
chunks_to_show = 10
chunk_inds = RNG.choice(len(bundle.df_chunks), 10, replace=False)
df_inspect = bundle.df_chunks.loc[chunk_inds]
df_inspect = pd.merge(df_inspect, bundle.df_sources, left_on='source_ind', right_index=True, how='left')
df_inspect.rename(columns={'name': 'source_name', 'fname': 'source_fname'}, inplace=True)
df_inspect['chunk1'] = df_inspect['chunk'].map(lambda c: list(map(lambda t: bundle.df_vocab.iloc[t].text, c)))

sources = {}

for row in df_inspect.itertuples():
    print(f'Chunk #{row.Index}, source={row.source_name} (#{row.source_ind}), lines={row.start_line_ind}:{row.end_line_ind}')
    print('- as int list: |' + '|'.join(map(str, row.chunk)) + '|')
    print('- as str list: |' + '|'.join(map(str, row.chunk1)) + '|')
    
    if not row.source_name in sources:
        with open(row.source_fname, 'r', encoding='utf-8') as f:
            sources[row.source_name] = f.readlines()
        
    print('- origin:      ' + ''.join(sources[row.source_name][row.start_line_ind:row.end_line_ind+1]))
    print()

Chunk #2053781, source=the_mysterious_island (#2), lines=2867:2867
- as int list: |2|7|3|6|0|3|0|24|6|5|16|1|20|0|9|12|8|7|1|10|0|4|6|0|2|7|1|0|16|4|9|13|5|10|3|21|11|1|0|3|
- as str list: |t|h|a|n| |a| |k|n|i|f|e|,| |r|u|s|h|e|d| |o|n| |t|h|e| |f|o|r|m|i|d|a|b|l|e| |a|
- origin:      but the stranger, with no other weapon than a knife, rushed on the formidable animal, who turned to meet this new adversary.


Chunk #383180, source=crime_and_punishment (#0), lines=1270:1270
- as int list: |21|1|17|0|18|4|12|0|2|4|0|14|11|4|8|1|0|2|7|3|2|0|10|4|4|9|0|3|2|0|4|6|14|1|0|3|6|10|0|2|
- as str list: |b|e|g| |y|o|u| |t|o| |c|l|o|s|e| |t|h|a|t| |d|o|o|r| |a|t| |o|n|c|e| |a|n|d| |t|
- origin:      "you are not amalia ivanovna, but amalia ludwigovna, and as i am not one of your despicable flatterers like mr. lebeziatnikov, who's laughing behind the door at this moment (a laugh and a cry of 'they are at it again' was in fact audible at the door) so i shall always call you amalia ludwigovna, though i fail to understand why you dislike that name. you can see for yourself what has happened to semyon zaharovitch; he is dying. i beg you to close that door at once and to admit no one. let him at least die in peace! or i warn you the governor-general, himself, shall be informed of your conduct to-morrow. the prince knew me as a girl; he remembers semyon zaharovitch well and has often been a benefactor to him. everyone knows that semyon zaharovitch had many friends and protectors, whom he abandoned himself from an honourable pride, knowing his unhappy weakness, but now (she pointed to raskolnikov) a generous young man has come to our assistance, who has wealth and connections and whom semyon zaharovitch has known from a child. you may rest assured, amalia ludwigovna…"


Chunk #2158483, source=the_mysterious_island (#2), lines=3373:3375
- as int list: |1|11|8|22|25|25|7|12|9|9|3|7|0|16|4|9|0|7|1|9|0|14|3|19|2|3|5|6|28|25|25|7|12|9|9|3|7|0|16|4|
- as str list: |e|l|s|.|"|"|h|u|r|r|a|h| |f|o|r| |h|e|r| |c|a|p|t|a|i|n|!|"|"|h|u|r|r|a|h| |f|o|
- origin:      "she would show all the navy of norfolk a clean pair of heels."
"hurrah for her captain!"
"hurrah for bob harvey!"


Chunk #3880141, source=ulysses (#4), lines=5278:5279
- as int list: |6|10|8|0|4|16|0|6|3|2|12|9|1|22|2|7|1|0|23|1|5|11|1|10|0|8|5|21|18|11|35|0|30|40|8|2|3|21|8|0|
- as str list: |n|d|s| |o|f| |n|a|t|u|r|e|.|t|h|e| |v|e|i|l|e|d| |s|i|b|y|l|:| |_|(|s|t|a|b|s| |
- origin:      theodore purefoy: _(in fishingcap and oilskin jacket.)_ he employs a mechanical device to frustrate the sacred ends of nature.
the veiled sibyl: _(stabs herself.)_ my hero god! _(she dies.)_


Chunk #2058944, source=the_mysterious_island (#2), lines=2906:2906
- as int list: |3|5|10|0|7|1|20|0|25|2|7|1|0|14|4|9|9|3|11|0|7|3|8|0|4|6|11|18|0|8|2|3|21|11|1|8|0|7|3|9|
- as str list: |a|i|d| |h|e|,| |"|t|h|e| |c|o|r|r|a|l| |h|a|s| |o|n|l|y| |s|t|a|b|l|e|s| |h|a|r|
- origin:      "my friend," said he, "the corral has only stables hardly fit for animals."


Chunk #2845783, source=the_picture_of_dorian_gray (#3), lines=1173:1173
- as int list: |6|10|1|9|5|6|17|0|8|1|3|36|17|12|11|11|0|8|14|9|1|3|13|1|10|22|0|2|7|1|0|7|4|9|8|1|0|8|2|12|
- as str list: |n|d|e|r|i|n|g| |s|e|a|-|g|u|l|l| |s|c|r|e|a|m|e|d|.| |t|h|e| |h|o|r|s|e| |s|t|u|
- origin:      then they passed by lonely brickfields. the fog was lighter here, and he could see the strange, bottle-shaped kilns with their orange, fanlike tongues of fire. a dog barked as they went by, and far away in the darkness some wandering sea-gull screamed. the horse stumbled in a rut, then swerved aside and broke into a gallop.


Chunk #1876535, source=the_mysterious_island (#2), lines=2041:2041
- as int list: |12|13|1|0|4|16|0|15|3|2|1|9|0|5|6|0|2|7|1|0|9|1|10|0|14|9|1|1|24|0|15|3|8|0|14|4|6|8|5|10|
- as str list: |u|m|e| |o|f| |w|a|t|e|r| |i|n| |t|h|e| |r|e|d| |c|r|e|e|k| |w|a|s| |c|o|n|s|i|d|
- origin:      the western border of the plateau now remained between the turn of the river and the southern angle of the lake, a distance of about a mile, which was open to all comers. but nothing could be easier than to dig a broad deep ditch, which could be filled from the lake, and the overflow of which would throw itself by a rapid fall into the bed of the mercy. the level of the lake would, no doubt, be somewhat lowered by this fresh discharge of its waters, but cyrus harding had ascertained that the volume of water in the red creek was considerable enough to allow of the execution of this project.


Chunk #1495886, source=the_mysterious_island (#2), lines=374:374
- as int list: |2|0|15|3|8|0|14|4|13|19|3|9|3|2|5|23|1|11|18|0|16|11|3|2|20|0|16|4|9|0|2|7|1|0|15|5|6|10|0|19|
- as str list: |t| |w|a|s| |c|o|m|p|a|r|a|t|i|v|e|l|y| |f|l|a|t|,| |f|o|r| |t|h|e| |w|i|n|d| |p|
- origin:      they ascended towards the north, having on their left an interminable extent of billows, which broke with a deafening noise, and on their right a dark country, the aspect of which it was impossible to guess. but they felt that it was comparatively flat, for the wind passed completely over them, without being driven back as it was when it came in contact with the cliff.


Chunk #839486, source=crime_and_punishment (#0), lines=3070:3070
- as int list: |4|23|3|21|11|18|0|4|6|0|7|5|13|22|0|7|1|9|0|2|1|9|9|4|9|0|5|6|16|1|14|2|1|10|0|7|5|13|22|0|
- as str list: |o|v|a|b|l|y| |o|n| |h|i|m|.| |h|e|r| |t|e|r|r|o|r| |i|n|f|e|c|t|e|d| |h|i|m|.| |
- origin:      as soon as he had said this again, the same familiar sensation froze his heart. he looked at her and all at once seemed to see in her face the face of lizaveta. he remembered clearly the expression in lizaveta's face, when he approached her with the axe and she stepped back to the wall, putting out her hand, with childish terror in her face, looking as little children do when they begin to be frightened of something, looking intently and uneasily at what frightens them, shrinking back and holding out their little hands on the point of crying. almost the same thing happened now to sonia. with the same helplessness and the same terror, she looked at him for a while and, suddenly putting out her left hand, pressed her fingers faintly against his breast and slowly began to get up from the bed, moving further from him and keeping her eyes fixed even more immovably on him. her terror infected him. the same fear showed itself on his face. in the same way he stared at her and almost with the same _childish_ smile.


Chunk #329541, source=crime_and_punishment (#0), lines=1020:1020
- as int list: |14|0|16|1|3|9|0|2|7|3|2|0|7|3|10|0|7|3|12|6|2|1|10|0|7|5|13|0|4|16|0|11|3|2|1|22|0|5|2|0|
- as str list: |c| |f|e|a|r| |t|h|a|t| |h|a|d| |h|a|u|n|t|e|d| |h|i|m| |o|f| |l|a|t|e|.| |i|t| |
- origin:      but as soon as she went out, he got up, latched the door, undid the parcel which razumihin had brought in that evening and had tied up again and began dressing. strange to say, he seemed immediately to have become perfectly calm; not a trace of his recent delirium nor of the panic fear that had haunted him of late. it was the first moment of a strange sudden calm. his movements were precise and definite; a firm purpose was evident in them. "to-day, to-day," he muttered to himself. he understood that he was still weak, but his intense spiritual concentration gave him strength and self-confidence. he hoped, moreover, that he would not fall down in the street. when he had dressed in entirely new clothes, he looked at the money lying on the table, and after a moment's thought put it in his pocket. it was twenty-five roubles. he took also all the copper change from the ten roubles spent by razumihin on the clothes. then he softly unlatched the door, went out, slipped downstairs and glanced in at the open kitchen door. nastasya was standing with her back to him, blowing up the landlady's samovar. she heard nothing. who would have dreamed of his going out, indeed? a minute later he was in the street.